### ISSUE TITLE
Lab 5 / step "Start" :  PVC size must be 10 Gi

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-consulting/c8-devops-workshop#23]
```
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
```

with C8.3, the PVC Size must be 10 Gi minimum, else Zeebe does not want to start
`
io.camunda.zeebe.journal.JournalException$OutOfDiskSpace: Not enough space to allocate a new journal segment. Required: 2147483648, Available: 1003868160`
